---
- name: Deploy Docker Compose application to GCP instance
  hosts: all
  become: yes
  vars:
    app_directory: /opt/app
    compose_file: docker-compose.yml
  
  tasks:
    - name: Create application directory
      file:
        path: "{{ app_directory }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Deploy docker-compose.yml from template
      template:
        src: docker-compose.yml.j2
        dest: "{{ app_directory }}/{{ compose_file }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'
      register: compose_template

    - name: Pull latest Docker images
      shell: docker compose pull
      args:
        chdir: "{{ app_directory }}"
      become_user: "{{ ansible_user }}"
      
    - name: Start/recreate services with docker-compose up -d
      shell: docker compose up -d --remove-orphans
      args:
        chdir: "{{ app_directory }}"
      become_user: "{{ ansible_user }}"