all:
  hosts:
    app-server:
      ansible_host: "{{ server_ip }}"
      ansible_user: nivela
      ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars:
    ansible_become: yes
    ansible_become_method: sudo