name: Provision GCP server

on:
  workflow_dispatch:

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_KEY }}" > ~/.ssh/kejahunt_key
        chmod 600 ~/.ssh/kejahunt_key

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run provisioning playbook
      run: |
        ansible-playbook ansible/provisioning.yml \
          -i ansible/inventory.yml \
          -e "server_ip=${{ secrets.GCP_IP }}" \
          -e "ssh_private_key_file=~/.ssh/kejahunt_key"